apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.sqlOnFhir.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: sql-on-fhir
        image: {{ .Values.sqlOnFhir.image | quote }}
        imagePullPolicy: {{ .Values.sqlOnFhir.imagePullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        {{- if .Values.sqlOnFhir.healthProbes.enabled }}
        startupProbe:
          httpGet:
            path: {{ .Values.sqlOnFhir.healthProbes.path }}
            port: http
          initialDelaySeconds: {{ .Values.sqlOnFhir.healthProbes.startupProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.sqlOnFhir.healthProbes.startupProbe.periodSeconds }}
          failureThreshold: {{ .Values.sqlOnFhir.healthProbes.startupProbe.failureThreshold }}
        livenessProbe:
          httpGet:
            path: {{ .Values.sqlOnFhir.healthProbes.path }}
            port: http
          periodSeconds: {{ .Values.sqlOnFhir.healthProbes.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.sqlOnFhir.healthProbes.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.sqlOnFhir.healthProbes.path }}
            port: http
          periodSeconds: {{ .Values.sqlOnFhir.healthProbes.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.sqlOnFhir.healthProbes.readinessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.sqlOnFhir.resources }}
        resources:
          {{- toYaml .Values.sqlOnFhir.resources | nindent 10 }}
        {{- end }}
        env:
        {{- if .Values.sqlOnFhir.persistence.enabled }}
        - name: DB_PATH
          value: "/app/data/db.sqlite"
        {{- end }}
        {{- range $configKey, $configValue := .Values.sqlOnFhir.config }}
        - name: {{ $configKey }}
          value: {{ $configValue | quote }}
        {{- end }}
        {{- if .Values.sqlOnFhir.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /app/data
        {{- end }}
      {{- if .Values.sqlOnFhir.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
      {{- end }}
      {{- with .Values.sqlOnFhir.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sqlOnFhir.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sqlOnFhir.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
