{{- if .Values.sqlOnFhir.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
  - {{ .Values.sqlOnFhir.persistence.accessMode }}
  {{- if .Values.sqlOnFhir.persistence.storageClass }}
  storageClassName: {{ .Values.sqlOnFhir.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sqlOnFhir.persistence.size }}
{{- end }}
